DELIMITER $$

CREATE TRIGGER AfterUserInsert
AFTER INSERT
ON Users FOR EACH ROW
BEGIN
    INSERT INTO Spades (USER_ID) VALUES NEW.ID;
    INSERT INTO Euchre (USER_ID) VALUES NEW.ID;
END$$

DELIMITER ;